apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-java-app
  labels:
    app: dummy-java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-java-app
  template:
    metadata:
      labels:
        app: dummy-java-app
    spec:
      containers:
      - name: dummy-java-app
        image: hamzaamish/dummy-java-app:latest
        ports:
        - containerPort: 8080

