apiVersion: v1
kind: Service
metadata:
  name: dummy-java-app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    app: dummy-java-app
    
  

